name: Release-pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  source-and-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
         version: '3.15.7'

      - name: Install dependencies
        run: |
          make deps

      - name: Build binaries
        run: |
          make release

      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: "false"
          onlyLastTag: "true"
          stripGeneratorNotice: "true"
          issuesWoLabels: "true"
          stripHeaders: "true"

      - name: Release fuseml-core
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/*
          body_path: ./CHANGELOG.md
          prerelease: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-iamge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
         version: '3.15.7'

      - name: Install dependencies
        run: |
          make deps

      - name: Set image name and tag
        run: |
          echo "IMG=ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
         
      - name: Build image
        run: |
          make docker-build

      - name: Push image
        run: |
          make docker-push
